service: cognito-custom-message-service

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3 # Update to your desired AWS region

functions:
  customMessageFunction:
    handler: handler.handler
    events:
      - cognitoUserPool:
          pool: Login and registration # Update this with your user pool name
          trigger: CustomMessage
          existing: true

